### PR TITLE
Add 'Trending Metrics' scheduled email report

### PR DESCRIPTION
**Pull request by jfeldstein**

### CODE REVIEW

**Comment by hex337** [comment]
@josephwegner Hrm, didn't know we had this sitting around in here, but definitely something we should look at. It looks good to me, just needs a bit of a README and example email pic I think.

**Comment by josephwegner** [comment]
super cool. Sorry for the delay @jfeldstein. This has some merge conflicts now, but I think it's great.

**Comment by jfeldstein** [comment]
CI is failing, too. 

Should I bother rebasing this?

**Comment by josephwegner** [comment]
I think you can ignore CI for this one… but if you want this added, then a
rebase would be necessary. On Tue, Apr 5, 2016 at 2:26 PM Jordan Feldstein <notifications@github.com>
wrote:
CI is failing, too.

Should I bother rebasing this?

**Comment by jfeldstein** [comment]
Rebased but still getting merge conflicts: 

```
$ git rebase keen/master
Current branch email_trending_metrics is up to date.
```

Ideas?

**Comment by jfeldstein** [comment]
Conflicts were just in the Readme, btw.

**Comment by jfeldstein** [comment]
All green!

**Pull request merged**
